
# Site settings

url: "https://sanspace.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: /personal
permalink: /:title/
highlighter: pygments

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally

force-https: True

#############
# HTML Head #
#############

author: "Santhosh Kumar Srinivasan"
lang: "en"
title: "Sanspace"
favicon: "/img/favicon.ico"
description: "Blog and website of Santhosh Kumar Srinivasan, blogging mainly for tech. Opinions expressed are mine."
keywords: "sanspace, santhosh, srinivasan, jekyll, theme"

################
# Intro layout #
################

black-favicon: "/img/black-favicon.ico"
background-img: "../img/intro-bg.jpg"
me-img: "/img/san-portrait.png"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "Jack of many, Master of few."
  - text: "Code is Poetry!"
  - text: "There is no spoon!"
  

########
# Blog #
########

post-preview-words: 96

paginate: 5

fb-share: True
twitter-share: True
reddit-share: True
disqus-shortname: "sanspace"

###############
# Life Events #
###############

events:
  - image: "/img/career/cognizant.png"
    date: "October 2009 - Today"
    description: "Senior Developer - C, Unix!"
  - image: "/img/career/infosys.png"
    date: "September 2008 - October 2009"
    description: "Assistant Engineer - Testing"

# First image of the Career timeline
career-img: "/img/career/san.jpg"

##################
# Contact layout #
##################

email: "san@sanspace.in"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/santhoshkumar.srinivasan"
  - title: "twitter"
    url: "https://twitter.com/2sks"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/santhoshkumarsrinivasan"
  - title: "github"
    url: "https://github.com/sanspace"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/340236/san"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Navigation bar links
# Blog link in the blog and post pages will point to the blog.html#blog
# In the default page it will point to the preview of the last post


github-info:
  handle: "sanspace"
  repo-desc-char-limit: 50
  repo-display-limit: 2

pages_list:
  About: 'about'
  Blog: 'blog'
  Career: 'career'
  Contact: 'contact'
  Code: 'code'

# Pagination path
paginate_path: "blog/page:num"

# Enable minification SASS
sass:
  style: compressed

# Exclusion list from the generated _site
exclude: ["Rakefile", "LICENSE", "readme.markdown", "vendor"]

gems: [jekyll-paginate]
